version: "3"
services:
  front-end:
    build: ./Front
    ports:
      - 1213:3000
    volumes:
      - ./Front:/home/front

  back-end:
    build: ./app
    ports:
      - 1214:3001
    volumes:
      - ./app:/home/back

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Renegades
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Victor123@#!
    ports:
      - "1215:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 1216:8080
